### ISSUE TITLE
Add a docker container option to run Milton

### ISSUE THREAD

**Issue by MrHedmad** [MrHedmad/Milton#27]
Deploying an instance is easy, but sometimes - due to Python versioning and some other external requirements that apparently not everyone has (*cough* poppler *cough*) - it can be a pain. 

Write a Dockerfile to generate a Docker image, so that deployment is easier.

## TODO
- [ ] Write a dockerfile;
- [ ] Add an auto-deploy-to-dockerhub action on release;
- [ ] Write an utility script that pulls the image if needed, mounts the volumes as needed and runs the bot instance;
- [ ] Add to the README this possibility (with those cool and super unsafe 'Run `wget ... | sh` and get started in seconds!' bits)
